### ISSUE TITLE
Model hot-reload crash

### ISSUE THREAD

**Issue by Vswe** [dan200/Redirection#30]
When reloading in the editor (F5) the game crashes if one of the models (.obj) has received any new subobjects. I haven't figured out exactly what is required to make it crash but I have done some tests:

Adding new vertices are fine, no crash.
Adding new texture vertices are fine, no crash.
Adding new faces are fine, no crash.
Adding new empty subobject are fine, no crash.
Making a new subobject with new vertices, texture vertices and faces is not allowed, it crashes.

    Game crashed with System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at Dan200.Core.Render.Model.Draw(ModelEffectInstance effect, Matrix4[] transforms, Boolean[] visibility, Single alpha)
       at Dan200.Game.Robot.Robot.OnDraw(ModelEffectInstance modelEffect)
       at Dan200.Game.Level.Level.Draw(ModelEffectInstance effect)
       at Dan200.Game.Level.Level.Draw(Camera camera, Boolean drawShadows, Boolean drawLights)
       at Dan200.Game.Game.LevelState.CommonDraw()
       at Dan200.Game.Game.EditorState.OnDraw()
       at Dan200.Game.Game.Game.Render()
       at Dan200.Core.Main.App.Run[TGame](GameInfo info, String[] args)

Starting the game again loads the model perfectly fine, the crash is caused by the in-game reload.

**Comment by dan200** [comment]
Hot reload is a debug feature, it doesn't have to be perfect :)
